/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class main_Root */

#ifndef _Included_main_Root
#define _Included_main_Root
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     main_Root
 * Method:    root
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_main_Root_root
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
