/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class main_SquaredWrapper */

#ifndef _Included_main_SquaredWrapper
#define _Included_main_SquaredWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     main_SquaredWrapper
 * Method:    square
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_main_SquaredWrapper_square
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
